Release v1.12.1 (#2128)
* Add MIPS32 cross compilation, refactor existing cross-compilation jobs (#2091)

* MIPS32 cross compilation, threadpool, and use DRY

* Add the ZLIB changes too

* Address comment

* Add opus sample frame generation GStreamer command to the readme (#2098)

* Add data channel option to the readme (#2099)

* Add data channel option to the readme

* Address comments

* Fixing the SPS/PPS/VPS for the H.265 samples to ensure that Safari playback does not pause. (#2111)

* Upgrade to Ubuntu 22, refactor CI to use DRY, seperate the jobs (#2116)

* Upgrade to Ubuntu 22, refactor CI to use DRY, seperate the jobs

* Additional cleanup

* Fix the uint16 promotion case (#2101)

* Cleaning up stale resources, adjusted logging (#2117)

* Global log level

* Add progress bar and run the deletion script

* Undo git_shallow for non-tagged versions

* Install dependencies for AWS SDK CPP

* Use ubuntu 22 container for the codecov

* Downgrade to Ubuntu 20

* Add CD and change to bash

* Install curl

* Increase history for codecov

* Seperate the steps for generating the report and uploading it

* Configure LWS logs with KVS log level (#2118)

* getNatBehaviorStr: Fix function return value compile error (#2114)

- Following error was seen:
  `In function 'getNatBehaviorStr': NatBehaviorDiscovery.c:385:1: error: control reaches end of non-void function [-Werror=return-type]`
 - Fixed this by returning `NAT_BEHAVIOR_NONE_STR`

* Allow branches named with pattern 'test-pr-*' to trigger the CI (#2120)

* Increase the signaling message receive buffer size (#2126)

* Increase the buffer sizes to accomodate for H.265 support in Chrome

* Bump the project version to 1.12.1

* 2x was too much, make it less

---------

Co-authored-by: Siva Somasundaram <34496097+unicornss@users.noreply.github.com>
Co-authored-by: Vikram Dattu <dattuvikram@gmail.com>