Miscellaneous build fixes (#2147)
* bugfix(kvspicUtils): Implicit declaration error on pthread_getname_np

Following error was observed while building sources with gcc14:
```
 kvspic-src/CMakeFiles/kvspicUtils.dir/src/utils/src/Thread.c:155:16: error: implicit declaration of function 'pthread_getname_np' [-Wimplicit-function-declaration]
  155 |     retValue = pthread_getname_np((pthread_t) thread, name, len);
      |                ^~~~~~~~~~~~~~~~~~
gmake[5]: *** [dependency/libkvspic/kvspic-src/CMakeFiles/kvspicUtils.dir/build.make:426:
```

 - Fixed by explicitly passing `-D_GNU_SOURCE` flag to make
   `pthread_getname_np` visible from `pthread.h`

* Move ifaddrs.h and poll.h under macro checks

 - Check in CMake if these headers available and set pass HAVE_<header>_H flag
 - Wrap the header includes under this flag

* Check in CMake, if socketpair available on the platform and use the flag

 - Instead of assuming that socketpair functionality available on
non-windows platforms, check if the function exists via CMakeList and
use flag to guard the kicksocket code under the macro